name: CI

on:
  push:
    branches: 
    - main
    - develop
    paths-ignore:
    - 'docs/**'
    - '*.md'
    - '.github/**'
    - '.gitignore'
    - '.gitattributes'
    - 'LICENSE'
  pull_request:
    branches: 
    - main
    paths-ignore:
    - 'docs/**'
    - '*.md'
    - '.github/**'
    - '.gitignore'
    - '.gitattributes'
    - 'LICENSE'
  release:
    types: [ published ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025]
        platform: [x64, x86]  # Changed from Win32 to x86
        configuration: [Debug, Release]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Detect installed Windows 10 SDK version
      id: detect-winsdk
      shell: pwsh
      run: |
        $sdkLib = "${Env:ProgramFiles(x86)}\Windows Kits\10\Lib"
        if (-not (Test-Path $sdkLib)) {
          Write-Error "Windows 10 SDK Lib directory not found at $sdkLib"
          exit 1
        }
        $versions = Get-ChildItem $sdkLib -Directory |
          Where-Object { $_.Name -match '^\d+\.\d+\.\d+\.\d+$' } |
          Select-Object -ExpandProperty Name
        if (-not $versions) {
          Write-Error "No Windows 10 SDK versions found under $sdkLib"
          exit 1
        }
        $selected = $versions | Sort-Object {[Version]$_} -Descending | Select-Object -First 1
        Write-Host "Using WindowsTargetPlatformVersion=$selected"
        "WIN_SDK_VERSION=$selected" | Out-File -FilePath $Env:GITHUB_ENV -Append

    - name: Restore NuGet packages
      run: nuget restore "RPG Maker Unpacker.sln"

    - name: Build solution
      run: |
        msbuild "RPG Maker Unpacker.sln" `
          /p:Configuration=${{ matrix.configuration }} `
          /p:Platform=${{ matrix.platform }} `
          /p:WindowsTargetPlatformVersion=${{ env.WIN_SDK_VERSION }} `
          /p:UseEnv=true `
          /m `
          /verbosity:minimal

    - name: Upload build artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: rpg-maker-unpacker-${{ matrix.os }}-${{ matrix.platform }}
        path: |
          ${{ matrix.platform }}/${{ matrix.configuration }}/*.exe
          ${{ matrix.platform }}/${{ matrix.configuration }}/*.dll
          ${{ matrix.platform }}/${{ matrix.configuration }}/*.pdb
        if-no-files-found: error
        compression-level: 9
        retention-days: 30

  code-analysis:
    name: Code Analysis
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: cpp
        queries: security-and-quality

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Detect installed Windows 10 SDK version
      id: detect-winsdk-codeql
      shell: pwsh
      run: |
        $sdkLib = "${Env:ProgramFiles(x86)}\Windows Kits\10\Lib"
        $versions = Get-ChildItem $sdkLib -Directory |
          Where-Object { $_.Name -match '^\d+\.\d+\.\d+\.\d+$' } |
          Select-Object -ExpandProperty Name
        $selected = $versions | Sort-Object {[Version]$_} -Descending | Select-Object -First 1
        "WIN_SDK_VERSION=$selected" | Out-File -FilePath $Env:GITHUB_ENV -Append
        Write-Host "Using WindowsTargetPlatformVersion=$selected for CodeQL build"

    - name: Restore NuGet packages
      run: nuget restore "RPG Maker Unpacker.sln"

    - name: Build for CodeQL
      run: |
        msbuild "RPG Maker Unpacker.sln" `
          /p:Configuration=Release `
          /p:Platform=x64 `
          /p:WindowsTargetPlatformVersion=${{ env.WIN_SDK_VERSION }} `
          /m

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  release:
    name: Create Release
    needs: [build, code-analysis]
    runs-on: windows-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create release packages
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "release" | Out-Null
        $pairs = @(
          @{ Path="artifacts/rpg-maker-unpacker-windows-2022-x64"; Zip="release/RPG-Maker-Unpacker-windows-2022-x64.zip" }
          @{ Path="artifacts/rpg-maker-unpacker-windows-2022-x86"; Zip="release/RPG-Maker-Unpacker-windows-2022-x86.zip" }
          @{ Path="artifacts/rpg-maker-unpacker-windows-2025-x64"; Zip="release/RPG-Maker-Unpacker-windows-2025-x64.zip" }
          @{ Path="artifacts/rpg-maker-unpacker-windows-2025-x86"; Zip="release/RPG-Maker-Unpacker-windows-2025-x86.zip" }
        )
        foreach ($p in $pairs) {
          if (Test-Path $p.Path) {
            Compress-Archive -Path "$($p.Path)/*" -DestinationPath $p.Zip -Force
            Write-Host "Packaged $($p.Zip)"
          }
        }

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/*.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security-scan:
    name: Security Scan
    runs-on: windows-latest
    continue-on-error: true
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'